name: Build iOS FFI (Rust -> Swift)

on:
  pull_request:
    branches: [ main ]

jobs:
  build-ios:
    name: Build iOS Targets
    runs-on: macos-latest

    env:
      RUST_BACKTRACE: 1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - run: rustup toolchain install $(cat rust-toolchain) --profile minimal --target x86_64-apple-ios,aarch64-apple-ios,aarch64-apple-ios-sim --component rust-src

    - run: brew install protobuf

    - name: Build for x86_64-apple-ios
      run: CARGO_BUILD_TARGET=x86_64-apple-ios swift/build_ffi.sh --release

    - name: Build for aarch64-apple-ios-sim
      run: CARGO_BUILD_TARGET=aarch64-apple-ios-sim swift/build_ffi.sh --release

    - name: Build for aarch64-apple-ios
      run: CARGO_BUILD_TARGET=aarch64-apple-ios swift/build_ffi.sh --release

    - name: Create .tar.gz archive of built libraries
      run: |
        mkdir -p build_artifacts
        VERSION_TAG=$(echo "${GITHUB_HEAD_REF}" | sed 's|.*/||' | sed 's|.*-||')
        ARCHIVE_NAME="libsignal-client-ios-build-${VERSION_TAG}.tar.gz"
        tar -czf build_artifacts/$ARCHIVE_NAME \
          target/aarch64-apple-ios/release/libsignal_ffi.a \
          target/x86_64-apple-ios/release/libsignal_ffi.a \
          target/aarch64-apple-ios-sim/release/libsignal_ffi.a
        echo "ARCHIVE_NAME=$ARCHIVE_NAME" >> $GITHUB_ENV
        echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV

    - name: Print SHA256 checksum
      run: |
        echo "SHA256 checksum:"
        shasum -a 256 build_artifacts/${ARCHIVE_NAME}

    - name: Upload .tar.gz file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARCHIVE_NAME }}
        path: build_artifacts/${{ env.ARCHIVE_NAME }}
